

import type { Metadata } from "next";

import "../frontend/styles/globals.css";
import Navbar from "../frontend/components/common/Navbar";
import HamburgerMenu from "../frontend/components/common/HamburgerMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
