import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../frontend/styles/globals.css";
import { AuthProvider } from "../frontend/context/AuthContext";
import Avatar from "../frontend/components/common/Avatar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#070B1E]`}
      >
        <AuthProvider>
          <div className="relative min-h-screen">
            {/* Header */}
            <header className="w-full flex justify-end items-center px-6 py-4 fixed top-0 left-0 z-50 bg-[#070B1E]/80 backdrop-blur border-b border-white/10">
              <Avatar />
            </header>
            <main className="pt-20">
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
