
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../frontend/styles/globals.css";
import ClientLayout from "./_components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#070B1E]`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
